export const SAVE_AUTH = "SAVE_AUTH";
export const REMOVE_AUTH = "REMOVE_AUTH";

export const GET_POSTS_PERSONAL_REQUEST = "GET_POSTS_PERSONAL_REQUEST";
export const GET_POSTS_PERSONAL_SUCCESS = "GET_POSTS_PERSONAL_SUCCESS";
export const GET_POSTS_PERSONAL_FAIL = "GET_POSTS_PERSONAL_FAIL";

export const GET_POSTS_HOME_REQUEST = "GET_POSTS_HOME_REQUEST";
export const GET_POSTS_HOME_SUCCESS = "GET_POSTS_HOME_SUCCESS";
export const GET_POSTS_HOME_FAIL = "GET_POSTS_HOME_FAIL";

export const GET_POSTS_FRIEND_REQUEST = "GET_POSTS_FRIEND_REQUEST";
export const GET_POSTS_FRIEND_SUCCESS = "GET_POSTS_FRIEND_SUCCESS";
export const GET_POSTS_FRIEND_FAIL = "GET_POSTS_FRIEND_FAIL";

export const DELETE_POST_REQUEST ="DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS ="DELETE_POST_SUCCESS"
export const DELETE_POST_FAIL ="DELETE_POST_FAIL"

export const POST_COMMENT = "POST_COMMENT"
export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"




